### ISSUE TITLE
Incorrect in-frame/out-of-frame prediction?

### ISSUE THREAD

**Issue by NM-G08** [kidsneuro-lab/SpliceVault#16]
Hello,

I was reviewing the predictions for the donor site of exon 8 in TSC2 (NM_000548).  The fourth ranked prediction is for use of a cryptic site at +79.  When I reviewed this manually, I saw that this inserts a sequence that is technically in-frame but has a PTC just before the cryptic site (c.774+73_774+75).  Should this be coming up as an in-frame prediction or does the algorithm not look at the sequence for possible in-frame PTCs?

![image](https://github.com/kidsneuro-lab/SpliceVault/assets/43679337/0a45e285-a9ee-4867-85cd-774203ccc7b0)

Thanks for your help!
NM

**Comment by h-joshi** [comment]
Dear NM, Apologies for the delay in getting back to you. You're right - SpliceVault does not look at the sequence for possible in-frame PTCs. This is something we're hoping to address in future.

**Comment by NM-G08** [comment]
No problem!  Thanks for letting me know!
