### ISSUE TITLE
Gene Name box not displaying all genes

### ISSUE THREAD

**Issue by chiyanlau** [kidsneuro-lab/SpliceVault#2]
I seem to be hitting a problem with the "Gene name" selection box - it is only displaying genes that start with "A", no other genes can be selected.

**Comment by h-joshi** [comment]
Thanks for reporting this. I'll add clarifications to the user interface. All genes aren't displayed by default mainly for performance reasons. If you type the gene name in the text box, it'll show recommendations. See screenshot below

![image](https://user-images.githubusercontent.com/1222657/165687818-c8c12bdd-3463-4738-827f-6fe865a59ead.png)

Hope this helps.

**Comment by chiyanlau** [comment]
Got it, thanks heaps!
